title: 果樹の根域制限栽培とスマート農業のGitobi
description: > # this means to ignore newlines until "baseurl:"
  根域制限栽培とITを活用した果樹のスマート農業、フルーツ工場事業を行っています。フルーツ工場で収穫したフルーツは Maiko ブランドで展開。また果樹の根域制限栽培に必要な資材やスマートかん水装置、根域制限栽培システムの販売を行なっています。

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.gitobi.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

permalink: /:categories/:year/:month/:day/:title/

sass:
  sass_dir: assets/css

plugins:
  - jekyll-feed

exclude:
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock
