title: Gitobi
description: > # this means to ignore newlines until "baseurl:"
  モノの情報を見れるようにするためのツールを提供しています。

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.gitobi.com" # the base hostname & protocol for your site
twitter_username: gitobi_inc
github_username:  gitobi

# Build settings
markdown: kramdown
theme: minima

exclude:
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock
